# Shell variables
# Generated by 'wal'
wallpaper='/home/lichti/Bilder/wallpapers/Red_Eclipse.png'

# Special
background='#0F0512'
foreground='#d3b8b6'
cursor='#d3b8b6'

# Colors
color0='#0F0512'
color1='#58202A'
color2='#74232A'
color3='#563E4B'
color4='#8C1C2B'
color5='#8E272C'
color6='#A45552'
color7='#d3b8b6'
color8='#93807f'
color9='#58202A'
color10='#74232A'
color11='#563E4B'
color12='#8C1C2B'
color13='#8E272C'
color14='#A45552'
color15='#d3b8b6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
