[files]
current_page=17
recent_files=/home/lichti/.vscode-oss/settings.json;/home/lichti/.vscode-oss/argv.json;/home/lichti/.config/chezmoi/chezmoi.toml;/home/lichti/Dokumente/asdf;/home/lichti/.ssh/id_rsa;/home/lichti/.ssh/id_rsa.pub;/home/lichti/.gitconfig;/home/lichti/.ssh/id_ed25519;/home/lichti/.ssh/id_ed25519.pub;/home/lichti/.config/waybar/config.ctl;
recent_projects=
FILE_NAME_0=972;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fhypr%2Fhyprland.conf;0;4
FILE_NAME_1=662;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fhypr%2Fanimations.conf;0;4
FILE_NAME_2=4001;None;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fwaybar%2Fconfig.ctl;0;4
FILE_NAME_3=170;None;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fwaybar%2Fmodules%2Ftaskbar.jsonc;0;4
FILE_NAME_4=750;None;0;EUTF-8;1;1;0;%2Fusr%2Fshare%2Fgrub%2Fthemes%2FXenlism-Arch%2Ftheme.txt;0;4
FILE_NAME_5=125;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fkitty%2Fkitty.conf;0;4
FILE_NAME_6=2554;None;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Ffastfetch%2Fconfig.jsonc;0;4
FILE_NAME_7=2654;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.zshrc;0;4
FILE_NAME_8=561;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fhypr%2Fuserprefs.conf;0;4
FILE_NAME_9=1732;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fhypr%2Fkeybindings.conf;0;4
FILE_NAME_10=381;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fkitty%2Ftheme.conf;0;4
FILE_NAME_11=721;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2F_kitty%2Ftheme.conf;0;4
FILE_NAME_12=171;Conf;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2F_kitty%2Fkitty.conf;0;4
FILE_NAME_13=33;None;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.gitconfig;0;4
FILE_NAME_14=0;None;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2FDokumente%2Fasdf;0;4
FILE_NAME_15=51;None;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.config%2Fchezmoi%2Fchezmoi.toml;0;4
FILE_NAME_16=0;JSON;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.vscode-oss%2Fargv.json;0;4
FILE_NAME_17=12;JSON;0;EUTF-8;1;1;0;%2Fhome%2Flichti%2F.vscode-oss%2Fsettings.json;0;4

[VTE]
last_dir=/home/lichti

[project]
session_file=
project_file_path=/home/lichti/Projekte

[geany]
treeview_position=156
msgwindow_position=368
geometry=0;0;583;728;1;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=0
position_find_y=0
position_replace_x=0
position_replace_y=0
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
