# Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
#
# Theme Elements & Colors for Hyprland.

# Elements
$hypr_border_size = 2
$hypr_gaps_in = 0
$hypr_gaps_out = 0
$hypr_gaps_ws = 0
$hypr_rounding = 9
$groupbar_font_family = Iosevka
$groupbar_font_size = 10

# Colors
$gradient_angle = 45deg
$active_border_col_1 = 0xFF8C1C2B
$active_border_col_2 = 0xFF58202A
$inactive_border_col_1 = 0xFF200e26
$inactive_border_col_2 = 0xFF30103a
$active_shadow_col = 0x66000000
$inactive_shadow_col = 0x66000000
$group_border_active_col = 0xFF74232A
$group_border_inactive_col = 0xFF563E4B
$group_border_locked_active_col = 0xFF58202A
$group_border_locked_inactive_col = 0xFF8C1C2B
$groupbar_text_color = 0xFFd3b8b6
