## Colors configuration
[colors]
alpha=1.0
foreground=d3b8b6
background=0F0512

## Normal/regular colors (color palette 0-7)
regular0=0F0512  # black
regular1=58202A  # red
regular2=74232A  # green
regular3=563E4B  # yellow
regular4=8C1C2B  # blue
regular5=8E272C  # magenta
regular6=A45552  # cyan
regular7=d3b8b6  # white

## Bright colors (color palette 8-15)
bright0=93807f   # bright black
bright1=58202A   # bright red
bright2=74232A   # bright green
bright3=563E4B   # bright yellow
bright4=8C1C2B   # bright blue
bright5=8E272C   # bright magenta
bright6=A45552   # bright cyan
bright7=d3b8b6   # bright white
